#SPDX-License-Identifier: MIT-0
---
# tasks file for zabbix
- name: start zabbix
  include_tasks: start-zabbix.yml
  when: ACTION == "start"

- name: stop zabbix
  include_tasks: stop-zabbix.yml
  when: ACTION == "stop"
