- name: stop zabbix-server
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: absent
  delegate_to: localhost
  connection: local
  run_once: true

- name: stop zabbix-agent
  community.docker.docker_container:
    name: zabbix-agent
    state: absent
