#SPDX-License-Identifier: MIT-0
---
# tasks file for wireguard
- name: start wireguard
  include_tasks: start-wireguard.yml
  when: ACTION == "start"

- name: stop wireguard
  include_tasks: stop-wireguard.yml
  when: ACTION == "stop"
